[program:iot-mqtt-consumer]
command=/usr/bin/php /var/www/iot-meter-pilot/artisan mqtt:consume-meter
process_name=%(program_name)s_%(process_num)02d
numprocs=1

autostart=true
autorestart=true
startretries=999
startsecs=5
stopwaitsecs=30

user=www-data
environment=HOME="/var/www",USER="www-data"

redirect_stderr=false
stdout_logfile=/var/log/supervisor/iot-mqtt-consumer.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/iot-mqtt-consumer.err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=3
